export default {
  STOP_LOADING: "STOP_LOADING",
  START_LOADING: "START_LOADING",
  START_SUCCESS: "START_SUCCESS",
  STOP_SUCCESS: "STOP_SUCCESS",
  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  LOAD_BOT_NUMS: "LOAD_BOT_NUMS",
  LOGINSUCCESS: "LOGINSUCCESS",
  LOGOUTSUCCESS: "LOGOUTSUCCESS",

  TEMP_ORDER: "TEMP_ORDER",
  FIRST_TRIP: "FIRST_TRIP",
  SECOND_TRIP: "SECOND_TRIP",
  SET_ROUND_TRIP: "SET_ROUND_TRIP",
  CURRENT_ORDER: "CURRENT_ORDER",
  ORDER_DETAIL_IN_PAYMENT: "ORDER_DETAIL_IN_PAYMENT",

  CURRENT_USER: "CURRENT_USER",
  FIRST_LOCAL_TRIP: "FIRST_LOCAL_TRIP",
  SECOND_LOCAL_TRIP: "SECOND_LOCAL_TRIP",
  SET_ROUND_TRIP_LOCALLY: "SET_ROUND_TRIP_LOCALLY",
  FIRST_LOCAL_TRIP_QUOTE: "FIRST_LOCAL_TRIP_QUOTE",
  SECOND_LOCAL_TRIP_QUOTE: "SECOND_LOCAL_TRIP_QUOTE",
  SET_MAP_TO_FALSE: "SET_MAP_TO_FALSE",
  SET_FIRST_MAP_TO_FALSE: "SET_FIRST_MAP_TO_FALSE",
  SET_SECOND_MAP_TO_FALSE: "SET_SECOND_MAP_TO_FALSE",
  CUSTOMER_DETAIL_IN_CUSTOMER: "CUSTOMER_DETAIL_IN_CUSTOMER",

  AFTER_PAYMENT: "AFTER_PAYMENT",
  SET_ORDER_DETAIL_TO_FALSE: "SET_ORDER_DETAIL_TO_FALSE",
  ORDER_HISTORY_FROM_CUSTOMER: "ORDER_HISTORY_FROM_CUSTOMER",
  SET_TRIP_CREATED: "SET_TRIP_CREATED",
  RESET_ORDER: "RESET_ORDER",
  RESET_LOCAL_STORAGE: "RESET_LOCAL_STORAGE",
  FLIGHT_LIST_IN_LORD: "FLIGHT_LIST_IN_LORD",
  ALL_RESOURCE_IN_CUSTOMER: "ALL_RESOURCE_IN_CUSTOMER",

  TRIP_DETAIL_IN_CUSTOMER: "TRIP_DETAIL_IN_CUSTOMER"
};
