export default {
  PICKUP_LOCATION: "PICKUP_LOCATION",
  PICKUP_LOCATION_AGAIN: "PICKUP_LOCATION_AGAIN",
  DROPOFF_LOCATION: "DROPOFF_LOCATION",
  DROPOFF_LOCATION_AGAIN: "DROPOFF_LOCATION_AGAIN",
  PICKUP_DATE: "PICKUP_DATE",
  PICKUP_DATE_AGAIN: "PICKUP_DATE_AGAIN",
  PICKUP_TIME: "PICKUP_TIME",
  PICKUP_TIME_AGAIN: "PICKUP_TIME_AGAIN",
  PASSENGER_AMOUNT: "PASSENGER_AMOUNT",
  PASSENGER_AMOUNT_AGAIN: "PASSENGER_AMOUNT_AGAIN",
  FLIGHT: "FLIGHT",
  FLIGHT_AGAIN: "FLIGHT_AGAIN",
  ROUND_TRIP: "ROUND_TRIP"
};
